# Generated by Django 4.2 on 2024-03-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="content.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="location",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="location",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Location"
            ),
        ),
    ]
