# Generated by Django 4.2 on 2024-03-11 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0003_alter_media_post_alter_post_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=2000, verbose_name="Content")),
                (
                    "posted_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Story_posted_time"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Story_Comment_Author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Story_Comment_Likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comment_from_Story",
                        to="content.story",
                    ),
                ),
            ],
        ),
    ]
